development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: king_database_development
  pool: 5
  username: kingsley
  password: onyeke
  template: template0

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: king_database_test
  pool: 5
  username: kingsley
  password: onyeke
  template: template0


production:
  adapter: postgresql
  database: king_database_production
  pool: 5
  timeout: 5000
  template: template0
